---
title: "Gov 50 Final Project"
author: "Samantha O'Connell"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the criminal justice system and wrongful convictions. The Death Penalty Information Center, an organization I've interned for in the past, recently released their "Death Penalty Census," a thorough tracking of all executions conducted in the US since 1972 and I would be particularly interested in interacting with this data. DPIC also has tracked every single death-row exoneration we have record of and I think this information would be a useful starting point for my inquiries into demographics about the defendants and victims and the states and counties in cases that were tainted by wrongful convictions. In light of the Biden administration's pardoning of all federal simple marijuana convictions, I'd be interested in tracking data about federal drug convictions in general, tracking different sentencing outcomes and demographics to see the potential disparities.



